version: '3.9'
services:
  db:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codogma-back
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  app:
    image: airatgaliev/codogma-back:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ~/codogma/users/avatars:/app/users/avatars
      - ~/codogma/articles/images:/app/articles/images
      - ~/codogma/categories/images:/app/categories/images
      - ~/codogma/compilations/images:/app/categories/images
      - ~/codogma/lucene/indexes:/app/lucene/indexes
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/codogma-back
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SECURITY_JWT_SECRET_KEY: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      SECURITY_JWT_EXPIRATION_TIME: 3600000
      user.avatar.upload-dir: /app/users/avatars
      article.image.upload-dir: /app/articles/images
      category.image.upload-dir: /app/categories/images
      compilation.image.upload-dir: /app/compilations/images
      spring.jpa.properties.hibernate.search.backend.directory.root: /app/lucene/indexes
    depends_on:
      - db