version: '3.9'
services:
  db:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: it-blog-back
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  app:
    image: airatgaliev/it-blog-back:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ~/it-blog/users/avatars:/app/users/avatars
      - ~/it-blog/posts/images:/app/posts/images
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/it-blog-back
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SECURITY_JWT_SECRET_KEY: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      SECURITY_JWT_EXPIRATION_TIME: 3600000
      user.avatar.upload-dir: /app/users/avatars
      post.image.upload-dir: /app/posts/images
    depends_on:
      - db